# Generated by Django 4.1 on 2022-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_desciption_college_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(default='Some String', max_length=500),
        ),
    ]
